# Config
# ========================================================================================

# Basic site info
title: "Optimization-in-the-Länd Workshop 2026"
description: "Official website for the Optimization-in-the-Länd Workshop 2026"
author: "Mathias Staudigl"

# URL settings
url: "https://jschnebel.github.io"   # GitHub Pages root
baseurl: "/optimization-laend.de"    # repo name for project site

# Theme
theme: jekyll-theme-hydejack

#Hydejack settings
hydejack:
  dark_mode:
    dynamic: false
    icon: false

theme_color: "#ffffff"
accent_color: "#4fb1ba" 


# Navigation
nav:
menu:
  - title: Program
    url: /program/
  - title: Venue
    url: /venue/
  - title: Organizers
    url: /organizers/

# Optional features
markdown: kramdown
highlighter: rouge
katex: true


accent_image:          /assets/schloss_mannheim.jpg
