# Config
# ========================================================================================

# Basic site info
title: "Optimization in the Länd Workshop 2026"
description: "Official website for the Optimization in the Länd Workshop 2026"
author: "Mathias Staudigl"

# URL settings
url: "https://jschnebel.github.io"   # GitHub Pages root
baseurl: "/optimization-laend.de"    # repo name for project site

# Theme
theme: hydejack

# Navigation
nav:
  - title: Home
    url: /
  - title: Schedule
    url: /schedule/
  - title: Speakers
    url: /speakers/
  - title: Contact
    url: /contact/

# Optional features
markdown: kramdown
highlighter: rouge